AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  DirectMethodLambda

  Sample SAM Template for DirectMethodLambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30 # API Gateway currently has a 30-second timeout hard limit.

Parameters:
  IotEndpoint:
    Type: String
    Description: AWS IoT Endpoint (ATS-signed).

Resources:
  DirectMethodFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          IOT_ENDPOINT:
            Ref: IotEndpoint
      Policies:
        # IoT policy
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - iot:Connect
              Resource: 'arn:aws:iot:*:*:client/directMethod_*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - iot:Publish
              Resource: 'arn:aws:iot:*:*:topic/device/*/methods/*/*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - iot:Subscribe
              Resource: 'arn:aws:iot:*:*:topicfilter/device/methods/res/+/*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - iot:Receive
              Resource: 'arn:aws:iot:*:*:topic/device/methods/res/*/*'
      Events:
        DirectMethodApi:
          Type: Api
          Properties:
            Path: '/thing/{thingName}'
            Method: POST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DirectMethodApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/thing/{thingName}"
  DirectMethodFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt DirectMethodFunction.Arn
  DirectMethodFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt DirectMethodFunctionRole.Arn
